#!/bin/sh
#
# Gradle start up script for POSIX generated by the Gradle wrapper.
#
APP_HOME=$(cd -P -- "$(dirname -- "$0")" > /dev/null && pwd -P) || exit
APP_BASE_NAME=${0##*/}
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

exec "$JAVACMD" \
    "-Xmx64m" "-Xms64m" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
