org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=false
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
